DROP TABLE IF EXISTS booktable;

CREATE TABLE IF NOT EXISTS booktable(
id INT AUTO_INCREMENT,
book_name VARCHAR(50) NOT NULL,
volume_num INT NOT NULL,
author_name VARCHAR(50) NOT NULL,
published_date DATE NOT NULL,
PRIMARY KEY(id)
);

DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
  ID INT NOT NULL,
  NAME VARCHAR(50),
  AGE INT,
  PRIMARY KEY(ID)
);